# Generated by Django 3.2.4 on 2021-06-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='not_seen',
            field=models.IntegerField(default=0),
        ),
    ]
