# Generated by Django 3.2.4 on 2021-06-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(upload_to='profile/%Y/%M/%D'),
        ),
    ]
